# Generated by Django 4.1.5 on 2023-01-21 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StudentManagementSystem', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='subjects',
            name='staff_id',
        ),
    ]
