# Generated by Django 4.1.5 on 2023-01-21 22:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('StudentManagementSystem', '0003_studentresult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentresult',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
