# Generated by Django 4.1.5 on 2023-01-22 14:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('StudentManagementSystem', '0004_alter_studentresult_student_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectRegistration',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('subject_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StudentManagementSystem.subjects')),
            ],
        ),
        migrations.RemoveField(
            model_name='students',
            name='course_id',
        ),
        migrations.DeleteModel(
            name='Teachers',
        ),
        migrations.DeleteModel(
            name='Students',
        ),
    ]
