# Generated by Django 4.1.5 on 2023-01-24 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentManagementSystem', '0008_alter_conversation_last_message_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='text',
            field=models.CharField(default='', max_length=300),
        ),
    ]
