# Generated by Django 4.1.5 on 2023-01-24 21:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('StudentManagementSystem', '0009_chatmessage_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='from_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
